config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'tourists/home' => 'tourists#home', as: :tourist_home
  patch 'tourists/:tourist_id/assigned_to/:entity/:id' => 'tourists#assigned_to', as: :tourist_assigned_to
  get 'agency_people/home' => 'agency_people#home', as: :agency_people_home
  resources :tourists, except: [:new, :create, :index]
  root to: 'main#index'
end

app/models/tourist.rb
class Tourist < ActiveRecord::Base
  has_one :profile, as: :profileable
  has_one :user, through: :profile 
  belongs_to :tour_guide
  belongs_to :translator
  delegate :email, to: :user
  
  def self.created_with(user_id)
    self.create { |role| role.create_profile(user_id: user_id) }
  end

  def self.find_by(options={})
    if options[:email]
      User.find_by(options).as_tourist
    else
      super
    end
  end
end

app/controllers/tourists_controller.rb
class TouristsController < ApplicationController

  def home
    @tourist = current_user.as_tourist
  end

  def edit
    @tourist = current_user.as_tourist
    @start_year = set_year(@tourist)
  end

  def update
    @tourist = current_user.as_tourist
    @start_year = set_year(@tourist)
    if @tourist.update_attributes(form_params)
      flash[:notice] = "Your profile was updated successfully."
      redirect_to tourist_home_path
    else
      render :edit
    end
  end

  def assigned_to
    tourist = Tourist.find(params[:tourist_id])
    attribute = "#{params[:entity]}_id=".to_sym
    if tourist.respond_to?(attribute)
      tourist.send(attribute, params[:id]) 
      tourist.save
      flash[:notice] = "Job Seeker was assigned successfully."
    else
      flash[:notice] = "Invalid assignment"
    end
    redirect_to agency_people_home_path
  end

  private
    def set_year(tourist)
      if tourist.year_of_birth
        Date.parse("#{tourist.year_of_birth}0101").year
      else
        Date.today.year - 16
      end
    end

    def form_params
      params.require(:tourist).permit(:year_of_birth)
    end
end

app/helpers/tourists_helper.rb
module TouristsHelper
end

app/views/tourists/_form.html.haml
.form-group
  .control-label.col-sm-2
    = f.label :year_of_birth, 'Year Of Birth'
  .col-sm-6
    = select_year(start_year, field_name: :year_of_birth,
                  start_year: start_year, end_year: start_year - 60,
                  prefix: 'tourist')

app/views/tourists/_info.html.haml
%table.table.table-hover#info_table{ style: 'margin-top: 20px;' }
  %tbody
    %tr
      %td
        %strong Email
      %td
        = mail_to tourist.email
      %td
    %tr
      %td
        %strong Year of Birth
      %td
        = tourist.year_of_birth
      %td
    %tr
      %td
        %strong Translator
      %td
        = tourist.translator
      %td
    %tr
      %td
        %strong Tour Guide
      %td
        = tourist.tour_guide
      %td

app/views/tourists/_list.html.haml
%table.table.table-hover#assign_table{ style: 'margin-top: 20px;' }
  %thead
    %tr
      %th
        %strong Email
      %th
        %strong Translator
      %th
        %strong Tour Guide
  %tbody
    - tourists.each do |tourist|
      %tr{ id: "tourist-#{tourist.id}" }
        %td
          = tourist.email
        %td
          - if tourist.translator
            = tourist.translator.email
          - elsif translator
            = link_to 'Be Translator', tourist_assigned_to_path(tourist,
              'translator', translator), method: :patch
        %td
          - if tourist.tour_guide
            = tourist.tour_guide.email
          - elsif tour_guide
            = link_to 'Be Tour Guide', tourist_assigned_to_path(tourist,
              'tour_guide', tour_guide), method: :patch

app/views/tourists/edit.html.haml
.row
  .col-sm-8.col-sm-offset-2
    %h1 Edit Profile
    %b
    = form_for @tourist, html: { class: 'form-horizontal' } do |f|
      = render 'shared/error_messages', object: f.object
      %br
      .clearfix
      = render partial: 'form', locals: { f: f, start_year: @start_year }
      .form-group
        .col-sm-2.col-sm-offset-2
          = f.submit 'Update', class: 'btn btn-primary'
        .col-sm-2.col-sm-offset-1
          = link_to 'Cancel', :back, class: 'btn btn-danger'

app/views/tourists/home.html.haml
.col-sm-3
  %h3
    Tourist
  = link_to 'Edit Profile', edit_tourist_path(@tourist)
.col-sm-9
  = render partial: 'info', locals: { tourist: @tourist }

app/views/tourists/new.html.haml
.col-xs-6.col-xs-offset-3
  .jumbotron
    %h2 Tourist Registration
    = form_for @tourist, html: { class: 'form-horizontal' } do |f|
      = render 'shared/error_messages', object: @tourist
      = f.fields_for :profile do |prf|
        = render 'users/subform', f: prf
      .form-group
        = f.button class: "btn btn-primary" do 
          Sign Up